language: node_js
node_js: 12
os: windows

before_install:
  - npm install -g yarn # https://github.com/travis-ci/travis-ci/issues/9445#issuecomment-494864992

script:
  - yarn build

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      branch: master
      tags: true
    api-key:
      secure: "g7n/+Ybn1bweJ4ABk2qauqsr04C2A26WgltkwO0C4N3XJUEVFWOnI1DJhNvP3UidRXYea+swfhLdT0Xz++/SuQ2PornNplFG2wX8Tj8DYnMbY9sEgPiNWdCeWWdl+hNmiy0IFT3fpK/JGb0pYWSsRxPlp8L5wKyzVudnIyirKlQ9Ire6i38QkRUWLbl/7MUkD9nzrFQrqYChI5KYjQLEjlnQcmbdy1q6GvbM6+7Syz5UkGbZCDq/ZhpYVCCOyDSOJqLd8CK0n0B0L5+S0QoxZq/liXb1k5tvu1vRTNr9GV1vC1uPaQebn2kaCW9jjA+CPoiXoPKTkV+YgeAnmSj/zsMVi5AzaVNR9NB/GvPBf+8EagbfpqqE7O1Ky0wvoFsVaFKeikvq+H8QDInoSG3noZkTfdCJRdpJodR425CXxj1LLBMbtZG/0SQEJQx1TGta1TspXGKMa4sZN8uBQVfcogCHYlgLfYkbwon58Jw08FS7PMR6Dr26IlygK//hL17loF3ozbVafBX8JzMtcMqSVP1W2/IyoSnH4/fOWF1dJzF35GfeRzV7qAW+R02nyl2RAwXEQEJRGaOluBa/j9wiOXOXLFg7vYwLMOKA5qx6WYxWFPlbV9Ka7qgBJfFhOFXFoLmr4l74AkYVvzMLpYVeccyFwfOFzQDdO5TcWBj+VZo="
    file_glob: true
    file:
      - out/*
