language: node_js
node_js: 12
os: windows

before_install:
  - npm install -g yarn # https://github.com/travis-ci/travis-ci/issues/9445#issuecomment-494864992

script:
  - yarn build

deploy:
  provider: releases
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api-key:
    secure: "DpRioVdMbQKvjIQJTAR2YW2rlJU7l6kh1bFYu+2B7yr226s1MBnxoQEWI6iFOdn56rxVUQeH4+Q2kzxkjIZqoDyVjaKzrHxjcXJd5mtG2FJ7qlFr9hx46SW+yPnxuIdSLqCZ1kPJ/nkivVLnVpLWJzaBqCVefAy8lv0Yqa0684MXTq3Lby6NCxPet3EfGOfVHOqoHowMlyAjNOU8mPv2lpMevF0nbCRe2lv0+FAX4x84nSWncBwFE4irP4fae2itXBhlNnPgeBCOlHXNiuLHRrPczcX5cH1qjt5HtdlI92VCn/KBHWZ6EB13Y5/qpeXWny5TFQ0UxMyokDNlUxQlpUuj+qiPZGxK7PayFlRyaTNcxezAhCdJSLWryxkngwdKKdqr4O9BbPXKt/xVRBLfHgeaRO8mgMeI1DOkkLZBr3tIRlLfBWbfKYZRK+nHgNXPM74oIrF3YgCgUX4bglzH82fAn8v93bfNXTLwj+QtfxGeIYhOR3zYxgtI80kYnw1Tzo7jiCWTIBWNUlSfI/KWk0F29x5HFsezyG3yZHGwnyXfAECnsB1JCKPhNEH7rW6ncUD9n+/5hA+QEUj6KM0cGOjnu986mir4wkiNSixt1XJxP/ExuurRTQV9TsfgFAIjRCIbz3vmhUWZFGEgPmQkj+fHC9PF/eQ5B4tcdmLJKOg="
  file_glob: true
  file:
    - out/*
